### PR TITLE
Move css outside

### PR DESCRIPTION
**Pull request by eou**
I moved most CSS style code out of sever.elm to make it simpler, about 700+ lines into editor.css.
Right now it works well I think.

### CODE REVIEW

**Review by MikaelMayer — CHANGES_REQUESTED** [review]
Ok this works for the Apache version of Editor, but this would break the Node version of Editor because it does not have access to this css file. Let's talk together on how to make this work on Node.js.

Basically, it will be a matter of modifying the building script `bundle.js` so that it would incorporate this css inline in all other 2 versions of `bin/server.js` that are `bin/server-npm-package.js` and `server-run.js` (it's already inlining the content of server.elm)

To make sure the CSS bundling works, make sure the css file is inside `Editor/`, that bin/server.js reads it (easier debugging and developing), and that the other two bundled versions actually Integrate it.

To test if the bundling works, instead of running `node bin/server.js`, run `node bin/server-run.js`. The other file is for npm packaging and cannot be tested, but if the -run version works, then it's fine.

**Comment by eou** [comment]
The css file is in the `Editor/`. 
I think the main reason is that Apache server and Node server have different root directory so the 'href' in <link> tag cannot satisfy two servers. 
And I think css should be placed in some cloud server which we can use its cdn url as the 'href' url in the production environment. In that way we can ignore the css file location problem.
By the way, why we need to support two different servers at the same time? 
Thanks.

**Comment by MikaelMayer** [comment]
The problem by putting the css on an external server is that is becomes
very slow to test new css, because we need to save the file locally, put it
on the server, and then run Editor. Whereas if the style file is inside
Editor, every time we modify it and we refresh the page, we see immediate
changes.

Apache server are most common on shared servers.
The node server is experimental and I could not find a way to install it on
shared servers, so it's mostly used locally as an application to open any
html file, so it's not aware of any domain.

**Comment by eou** [comment]
Thanks for explanation.
So I add two link tag for apache server and node server respectively. It seems a little rigid. :)

**Comment by MikaelMayer** [comment]
No let's not do it that way, first there is a typo (should not be apcahe
but apache), but second and more important we should not modify links that
way, else, they will be back-propagated on file save.
Let's talk this afternoon about the option I suggest, which is a bit more
time consuming but will be more worth I think

**Comment by eou** [comment]
It works for both apache and node server now. I have pushed .htaccess to TharzenWebsite repo.

**Review by MikaelMayer — APPROVED** [review]

**Pull request merged**
